import type { OntologyObject, OntologyProperty, OntologySnapshotV3, PhysicalTable } from "../packages/contracts/src/index.js";
import { finalizeSnapshot } from "../packages/domain/src/index.js";

export function property(id:string,label:string,meaning:OntologyProperty["meaning"],options:Partial<OntologyProperty>={}):OntologyProperty{return {id,name:id.replace(/^p_/,""),label,description:`${label} 属性`,dataType:meaning==="NUMBER"?"DECIMAL":meaning==="TIME"?"DATE":"VARCHAR",sourceColumn:id.replace(/^p_/,""),sensitive:false,meaning,unique:meaning==="ID",valueSearchable:["CODE","NAME","CATEGORY","BOOLEAN","GEOGRAPHY"].includes(meaning),...(meaning==="NUMBER"?{numericSpec:{kind:"CURRENCY",currency:"CNY",defaultAggregation:"SUM",aggregationBehavior:"ADDITIVE"}}:{}),visibility:"ANALYTICAL",synonyms:[],defaultDisplay:true,exportable:true,bindingPriority:50,...options};}
function entity(id:string,label:string,props:OntologyProperty[],sourceTableId=`t_${id.slice(2)}`):OntologyObject{return {id,name:id.slice(2),label,description:`${label}业务对象`,sourceTableId,status:"PUBLISHED",objectType:"ENTITY",grainPropertyIds:[props[0]!.id],grain:props[0]!.label,exampleQuestions:[],properties:props,synonyms:[],bindingPriority:50};}
export function validSnapshot(namespace="retail",version=1):OntologySnapshotV3{const order:OntologyObject={id:"o_order",name:"orders",label:"订单",description:"订单聚合事实",sourceTableId:"t_orders",status:"PUBLISHED",objectType:"EVENT",grainPropertyIds:["p_order_id"],grain:"订单 ID",defaultTimePropertyId:"p_order_date",exampleQuestions:[],synonyms:["销售订单"],bindingPriority:50,properties:[property("p_order_id","订单 ID","ID"),property("p_order_date","业务日期","TIME"),property("p_store_ref","店铺引用","ENTITY_REFERENCE"),property("p_sales","销售金额","NUMBER",{synonyms:["销售额"]}),property("p_cost","成本金额","NUMBER",{synonyms:["成本额"]})]};const store=entity("o_store","店铺",[property("p_store_id","店铺 ID","ID"),property("p_store_name","店铺名称","NAME",{synonyms:["店铺"]}),property("p_dept_ref","部门引用","ENTITY_REFERENCE")],"t_store");const dept=entity("o_dept","部门",[property("p_dept_id","部门 ID","ID"),property("p_dept_name","部门名称","NAME",{synonyms:["部门"]}),property("p_bu_ref","事业部引用","ENTITY_REFERENCE")],"t_dept");const bu=entity("o_bu","事业部",[property("p_bu_id","事业部 ID","ID"),property("p_bu_name","事业部名称","NAME",{synonyms:["事业部"]})],"t_bu");const base={schemaVersion:3 as const,namespace,version,status:"PUBLISHED" as const,publishedAt:"2026-09-04T00:00:00.000Z",objects:[order,store,dept,bu],relations:[
{id:"r_order_store",name:"订单关联店铺",sourceObjectId:"o_order",targetObjectId:"o_store",type:"REFERENCE" as const,cardinality:"MANY_TO_ONE" as const,joinExpression:"orders.store_ref = store.store_id",sourcePropertyId:"p_store_ref",targetPropertyId:"p_store_id",direction:"SOURCE_TO_TARGET" as const,required:false,enabled:true,fanoutRisk:"NONE" as const,status:"PUBLISHED" as const},
{id:"r_store_dept",name:"店铺关联部门",sourceObjectId:"o_store",targetObjectId:"o_dept",type:"HIERARCHY" as const,cardinality:"MANY_TO_ONE" as const,joinExpression:"store.dept_ref = dept.dept_id",sourcePropertyId:"p_dept_ref",targetPropertyId:"p_dept_id",direction:"SOURCE_TO_TARGET" as const,required:true,enabled:true,fanoutRisk:"NONE" as const,status:"PUBLISHED" as const},
{id:"r_dept_bu",name:"部门关联事业部",sourceObjectId:"o_dept",targetObjectId:"o_bu",type:"HIERARCHY" as const,cardinality:"MANY_TO_ONE" as const,joinExpression:"dept.bu_ref = bu.bu_id",sourcePropertyId:"p_bu_ref",targetPropertyId:"p_bu_id",direction:"SOURCE_TO_TARGET" as const,required:true,enabled:true,fanoutRisk:"NONE" as const,status:"PUBLISHED" as const}],metrics:[
{id:"m_sales",metricType:"BASE" as const,name:"sales",label:"销售额",description:"销售金额之和",objectId:"o_order",expression:"SUM(orders.sales)",definitionMode:"VISUAL" as const,sourcePropertyId:"p_sales",aggregation:"SUM" as const,format:"currency" as const,synonyms:["成交金额"],status:"PUBLISHED" as const},
{id:"m_cost",metricType:"BASE" as const,name:"cost",label:"成本额",description:"成本金额之和",objectId:"o_order",expression:"SUM(orders.cost)",definitionMode:"VISUAL" as const,sourcePropertyId:"p_cost",aggregation:"SUM" as const,format:"currency" as const,synonyms:[],status:"PUBLISHED" as const},
{id:"m_margin",metricType:"DERIVED" as const,name:"margin",label:"毛利率",description:"毛利额除以销售额",objectId:"o_order",expression:"(m_sales-m_cost)/m_sales",definitionMode:"VISUAL" as const,leftMetricId:"m_cost",rightMetricId:"m_sales",calculationOperator:"RATIO" as const,scale:100,aggregation:"CUSTOM" as const,format:"percent" as const,synonyms:[],status:"PUBLISHED" as const}],dimensionHierarchies:[{id:"h_org",name:"org",label:"组织层级",kind:"FIXED_LEVELS" as const,levels:[{objectId:"o_store",propertyId:"p_store_id"},{objectId:"o_dept",propertyId:"p_dept_id"},{objectId:"o_bu",propertyId:"p_bu_id"}],status:"PUBLISHED" as const}]};return finalizeSnapshot(base);}

export function physicalTables():PhysicalTable[]{const source=(id:string,name:string,columns:string[]):PhysicalTable=>({id,catalog:"internal",database:"retail",name,type:"TABLE",status:"MODELED",columns:columns.map(column=>({name:column,dataType:"VARCHAR",nullable:false,sensitive:false})),fingerprint:id,scannedAt:"2026-09-04T00:00:00.000Z"});return [source("t_orders","orders",["order_id","order_date","store_ref","sales","cost"]),source("t_store","store",["store_id","store_name","dept_ref"]),source("t_dept","dept",["dept_id","dept_name","bu_ref"]),source("t_bu","bu",["bu_id","bu_name"])];}
