export type ResponseField = { path: string; type: string; description: string };
const fields = (items: Array<[string,string,string]>): ResponseField[] => items.map(([path,type,description])=>({path,type,description}));
export const ENVELOPE_FIELDS = fields([
 ['requestId','string','本次请求标识。'],['namespace','string','本体命名空间；系统操作为 system。'],['ontologyVersion','number（可选）','本次实际使用的发布版本；系统操作可能省略。'],['status','string','业务状态；HTTP 200 不代表查询已完成。'],['data','object / array','本接口业务数据，结构见下方。'],['auditId','string','用于关联调用审计。'],['warnings','array','警告列表。'],['completeness.complete','boolean','是否完整；结合 truncated 和 nextCursor 判断。'],['completeness.truncated','boolean','是否有未返回数据。'],['completeness.nextCursor','string / null','下一页游标；查询分页保持版本、条件和参数一致。'],['error.code','string（失败时）','稳定错误码，用于程序分支。'],['error.message','string（失败时）','可读错误说明。'],['error.stage','string（失败时）','失败阶段，例如 binding、planning、session。'],['error.retryable','boolean（失败时）','是否适合重试。'],['error.action / error.details','string / object（可选）','修复建议及错误详情；失败时 data 可能不存在。']
]);
const snapshot = fields([['schemaVersion','number','快照格式版本，当前为 3。'],['namespace / version / status','string / number / string','命名空间、发布版本与状态。'],['objects[]','object[]','对象定义；含 id、label、objectType、properties、grainPropertyIds、primaryNamePropertyId。'],['objects[].properties[]','object[]','属性定义：id、label、meaning、sourceColumn、visibility、numericSpec、valueSearchable。'],['relations[]','object[]','对象及属性连接、方向、基数、启用状态和关系策略。'],['metrics[]','object[]','指标定义及聚合、公式、源属性或依赖指标。'],['dimensionHierarchies[]','object[]','层级定义、层次和字段映射。'],['axiomAssertions[] / inferredAssertions[]','object[]','固化公理和推论。'],['contentDigest / inferenceDigest','string','定义与推论摘要。'],['publishedAt','string（可选）','发布时间。']]);
const draft = fields([['draftId','string','后续草稿操作使用的 ID。'],['baseVersion','number','草稿基线，用于发布并发校验。'],['revision','number','每次修改递增；修改请求提交最新值。'],['snapshot','object','当前草稿，结构同本体快照。'],['physicalTables[]','object[]','已扫描的物理表及字段。'],['validation','object（修改后）','valid 和 issues；保存成功仍需关注校验问题。'],['goldenReport','object（可选）','编译回归结果、运行时间和关联 revision。']]);
const index = fields([['status','string','empty / building / ready / partial / failed。'],['properties','number','参与索引的属性数。'],['valuesCount','number','已索引值数量。'],['coveredRows','number','覆盖行数。'],['failedProperties','number / null','失败属性数；空索引可能为 null。'],['updatedAt','string / null','最近更新时间。']]);
const source = fields([['sourceId','string','数据源标识。'],['configured','boolean（未配置时）','未配置时返回 false；已配置时返回 payload。'],['credentialConfigured','boolean（已配置时）','是否已保存密码，不代表连接测试通过。'],['payload','object（已配置时）','host、port、username、catalog、database、tls；不返回明文密码。'],['updatedAt','string（可选）','配置更新时间。']]);
const inference = fields([['id / predicate','string','推论标识和推论类型。'],['subjectId / objectId','string','关联定义标识，objectId 可选。'],['value','any','推论结论。'],['axiomAssertionIds[] / premiseAssertionIds[]','string[]','公理与前提引用。'],['proof[]','object[]','证明步骤，包含事实、公理、推导。'],['ontologyVersion','number','推论所属版本。']]);
const query = fields([['columns[]','string[]（成功时）','返回列名，按结果顺序排列。'],['rows[]','object[]（成功时）','结果行；对象键与 columns 对应。无匹配数据可为空数组。'],['rowCount / truncated','number / boolean','本次返回行数与截断状态。'],['ontologyVersion / resolutionMode','number / string','实际本体版本及查询模式。'],['businessSummary','object（INTENT 成功时）','业务口径摘要：metrics、dimensions、filters 和 time。'],['businessSummary.filters[]','object[]','每项含 object、property、value，说明实际筛选归属。'],['planId','string（成功时）','本次编译查询计划标识。'],['queryIr','object（可选）','options.includeQueryIr=true 返回：rootObjectId、measureIds、dimensionPropertyIds、filters、relationIds、timeRange、sort、limit。'],['sqlPreview','object（可选）','options.includeSqlPreview=true 返回 sql 与 parameters；参数值脱敏为问号。此开关仍会执行查询，不是仅预览。'],['resolution / ontologyContext','object（可选）','includeResolution / includeOntologyContext 控制绑定和上下文详情。'],['axioms / inferenceEvidence','array（可选）','includeAxioms / includeInferenceEvidence 控制规则和推论证据。'],['missing[]','object[]（NEEDS_INPUT）','field、term、reason；补充业务信息或修复定义后重新查询，不执行 SQL。'],['clarificationId','string（NEEDS_CLARIFICATION）','用于继续接口的路径参数，有效期 30 分钟。'],['clarifications[]','object[]（NEEDS_CLARIFICATION）','id、term、reason、candidates；每个候选含 id、label、object、property。selections 使用原样返回的候选 ID。'],['context / acceptanceContract','object（ANALYSIS_READY）','分析上下文与验收约束；该模式不执行数据查询。']]);
export const RESPONSE_FIELDS: Record<string, ResponseField[]> = {
 GetHealth: fields([['status','string','服务状态。'],['version / kernelVersion','string','服务与公理内核版本。'],['components','object','组件配置状态，不代表数据库可连接。'],['time','string','服务器时间。']]),
 GetOpenApiDocument: fields([['openapi','string','OpenAPI 版本。'],['info','object','服务标题与版本。'],['servers[]','object[]','API 根地址。'],['paths','object','各接口操作、参数、示例和响应说明。'],['components.schemas','object','请求及领域结构的 JSON Schema。']]),
 GetOntologySummary: fields([['ontologyVersion / status','number / string','实际版本和发布状态。'],['counts','object','对象、关系、指标、公理等数量。'],['contentDigest','string','定义摘要。'],['valueIndex','object','值索引状态。'],['defaultObject','object / null','默认对象。'],['graph','object','概览图谱。']]),
 GetOntologySnapshot:snapshot, PublishOntologyDraft:snapshot,
 GetOntologyGraph: fields([['ontologyVersion','number','版本。'],['nodes[]','object[]','图节点：标识、标签和类型。'],['edges[]','object[]','图连线：源、目标及关系信息。']]),
 ListOntologyVersions: fields([['[].version / [].status','number / string','版本及发布状态，按版本倒序。'],['[].publishedAt / [].publishedBy','string','发布时间与发布人。'],['[].changeSummary','string','变更说明。'],['[].objectCount / [].relationCount / [].metricCount','number','定义数量。'],['[].contentDigest / [].inferenceDigest','string','版本摘要。']]),
 DiffOntologyVersions: fields([['baseVersion','number','实际比较基线。'],['objects / relations / metrics / hierarchies / axioms / inferences','object','每类包含 added、changed、removed，用于展示增删改。']]),
 CreateOntologyDraft:draft,GetOntologyDraft:draft,PatchOntologyDraft:draft,
 ValidateOntologyDraft: fields([['valid','boolean','是否通过公理校验。'],['issues[]','object[]','校验问题：规则、位置及说明。'],['axiomAssertions[] / inferencePreview[]','object[]','公理和推论预览。'],['goldenCases','object','查询编译回归报告；只编译，不执行业务数据查询。'],['draftId / revision','string / number','被校验的草稿及修订号。'],['digests','object','content 和 inference 摘要。']]),
 ListAxiomAssertions:fields([['[].id / [].axiomCode','string','公理实例 ID 和规则编码。'],['[].subjectId / [].subjectType','string','约束对象及类型。'],['[].parameters','object','规则参数。'],['[].enforcement / [].severity','string','生效阶段与严重性。'],['[].sourceDefinitionIds[]','string[]','生成此公理的定义 ID。']]),
 ListInferredAssertions:inference.map(f=>({...f,path:`[].${f.path}`})),ExplainInference:inference,
 ResolveOntologyContext:fields([['sessionId / expiresAt','string','固定版本会话及过期时间。'],['ontologyVersion / projection','number / string','实际版本与投影模式。'],['bindings[]','object[]','term、role、status；BOUND 返回 selected，值绑定还返回 filter；AMBIGUOUS 返回 candidateReferences。'],['bindings[].selected','object','kind、id、objectId、propertyId；对象维度使用主名称属性。'],['candidates[]','object[]','候选类型、业务标签、所属对象及属性、匹配原因、优先级和可用用途。'],['values[]','object[]','匹配值及归属，filter 可用于 EQ 筛选。'],['retrieval','object','status、unmatchedTerms、notice；MATCHED、PARTIAL_MATCH、NO_MATCH、AMBIGUOUS。'],['ambiguities[]','object[]','待澄清词条、原因与候选。'],['objects[] / metrics[]','object[]','compact 为直接命中对象和指标摘要，standard/full 返回详细定义。'],['relations[] / hierarchies[] / relationPaths[]','object[]','standard/full 中返回相关构造信息；compact 为空数组。'],['axioms[] / inferences[]','object[]','include 对应开关显式开启时返回。'],['refs','object','兼容会话短引用映射；新调用可直接使用稳定 ID。'],['contextDigest / tokenEstimate','string / number','上下文摘要与估计 token 数。']]),
 ExecuteSemanticQuery:query,ContinueSemanticQuery:query,
 GetDataSource:[...source,...fields([['tables[]','object[]','已扫描表；含 name、comment、columns、fingerprint、scannedAt。']])],PutDataSource:source,
 TestDataSource:fields([['status','string','连接测试结果。'],['databaseVersion','string','数据库返回的版本。'],['elapsedMs','number','测试耗时，毫秒。']]),
 ScanDataSourceSchema:fields([['sourceId','string','扫描的数据源。'],['tables[]','object[]','表 ID、catalog、database、name、type、comment、status、fingerprint、scannedAt。'],['tables[].columns[]','object[]','name、dataType、nullable、comment、sensitive 等字段元数据。']]),
 GetValueIndexStatus:index,RebuildValueIndex:index,
 ListApiClients:fields([['[].clientId / [].name','string','客户端 ID 和名称。'],['[].scopes[]','string[]','已授权权限。'],['[].status','string','ACTIVE / DISABLED。'],['[].rateLimit','number','每分钟调用限额。'],['[].rotatedAt','string','密钥更新时间；列表不返回明文密钥。']]),
 CreateApiClient:fields([['clientId','string','新客户端 ID。'],['apiKey','string','新密钥，仅本次响应提供，立即安全保存。'],['warning','string','密钥保存提示。']]),RevokeApiClient:fields([['deleted','boolean','成功撤销为 true。']]),
 ListAuditEvents:fields([['[].auditId / [].requestId','string','审计与请求标识。'],['[].eventType','string','事件类型。'],['[].createdAt','string','发生时间。'],['[].payload','object','脱敏后的事件数据。']]),
 GetSystemMetrics:fields([['uptimeSeconds','number','进程已运行秒数。'],['memory','object','Node 进程内存统计，单位字节。'],['routes','object','按路由分组；count 调用数、errors 错误数、p95Ms 和 maxMs 延迟。']])
};
export const QUERY_RESPONSE_EXAMPLES = {
 success: {requestId:'req_example',namespace:'retail',ontologyVersion:1,status:'SUCCEEDED',data:{columns:['标准店名','销售金额'],rows:[{'标准店名':'示例店铺','销售金额':1200}],rowCount:1,truncated:false,ontologyVersion:1,resolutionMode:'INTENT',businessSummary:{metrics:['销售金额'],dimensions:['标准店名'],filters:[],time:'今年'},planId:'plan_example'},warnings:[],auditId:'audit_example',completeness:{complete:true,truncated:false,nextCursor:null}},
 missing: {status:'NEEDS_INPUT',data:{status:'NEEDS_INPUT',missing:[{field:'filter_0',term:'线上渠道',reason:'与指标对象之间没有可安全使用的关联路径'}]}},
 clarification:{status:'NEEDS_CLARIFICATION',data:{status:'NEEDS_CLARIFICATION',clarificationId:'clar_example',clarifications:[{id:'filter_0',term:'线上',reason:'请确认业务含义',candidates:[{id:'["value","value_example","p_channel"]',label:'线上',object:'组织单元',property:'组织单元名称'}]}]}},
 error:{status:'FAILED',error:{code:'INVALID_REQUEST',message:'请求参数不符合契约',stage:'binding',retryable:false}}
};
